agendas/2019-11-21.md

@IvanGoncharov do not merge just yet, awaiting confirmation.
@vladar i invite you to join this working group meeting. As the primary maintainer of graphql-php and the related server tools, i am sure you could contribute greatly to the discussion.

Maybe add @vladar

---

agendas/2019-11-21.md

Adding @hemanth to the list.

---

agendas/2019-11-21.md

4am Melbourne, Australia time 😱

Add Jayden Seric to 2019-11-21 meeting attendees

---

README.md

This prior art section seems useful as a starting point.

Add info about how the de-facto standard came to be

---

ROADMAP.md
agendas/2019-11-21.md

Add notes and actions from the Nov 21, 2019 call

Add notes and outcomes from Nov 21, 2019 call

---

working-group/agendas/2019-12-17.md

Add Jayden Seric to the 2019-12-17 meeting.

Add Jayden Seric to the 2019-12-17 meeting

---

working-group/agendas/2019-12-17.md

Add Jesse Rosenberger to 2019-12-17 agenda attendees.

---

README.md

Fixes #3. Sorry about the delay.

URL encoding of query strings

---

working-group/agendas/2020-05-26.md

Add Benjie to May WG

---

INTERESTED_DEVELOPERS.md

👋
I am interested in contributing to the GQL spec, more specifically in the area of subscriptions. Contradictory to [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws) being slowly abandoned, the need for realtime is blooming! Nevertheless, their 3-year-old [GraphQL over WebSocket Protocol](https://github.com/apollographql/subscriptions-transport-ws/blob/263844b5c1a850c1e29814564eb62cb587e5eaaf/PROTOCOL.md) is very relevant and highly used.
Lets splash some _modern_ water on it and standardise it!

Add @enisdenjo to list of interested developers

---

working-group/agendas/2020-06-30.md

Sorry for lateness, missed this (just saw it in Slack).

Add Benjie to June WG

---

working-group/agendas/2020-06-30.md

Hey, even though I have no agenda, yet, I'd like to attend the Working Group.

Add myself to working group

---

INTERESTED_DEVELOPERS.md

Use specification relevant project for @enidenjo

---

rfcs/IncrementalDelivery.md

Allow arbitrary boundaries in IncrementalDelivery RFC

---

spec/GraphQLOverHTTP.md

The example variables input is not valid JSON. (missing "")

Make sure the variables example is valid JSON

---

spec/GraphQLOverHTTP.md

This PR is an attempt to revive #83 by @sjparsons while modifying as little as possible.

Provide clarifications on content type and serialization

---

working-group/agendas/2022/2022-07-21.md

Create July 21st WG

---

spec/GraphQLOverHTTP.md

@glasser left some comments on #175; I've applied some of the fixes in this PR.
Generally these changes are either non-normative, or they're normatively stating things that we already agree on but happened to miss out of the text. As such, I think this PR can be merged after an approval or two if you agree @ghmcadams? (i.e. no need to delay)

Editorial recommendations from @glasser

---

working-group/agendas/2022/2022-07-21.md

Cc @enisdenjo @spawnia @michaelstaib @ghmcadams @mmatsa  
Delay start of meeting meeting by 2 hours as agreed in #184

Change time of July meeting

---

spec/GraphQLOverHTTP.md

I've not covered all of them, but hopefully enough to be helpful.
Part of #191

Add "Note" after various "SHOULD" rules in the spec

---

README.md
ROADMAP.md

As discussed in the July 2022 working group meeting,
we have now officially moved the spec to stage 1.

Reflect move to stage 1

---

working-group/public-apis.md

Remove melody.sh from public-apis.md

---

ROADMAP.md

Correct media type reference in ROADMAP.md

---

spec/GraphQLOverHTTP.md
spec/metadata.json

Resolves https://github.com/graphql/graphql-over-http/issues/230

Clarify well-formed response and fix links to GraphQL response spec

---

INTERESTED_DEVELOPERS.md

Closing and replacing #220 as it was very out of date. 
Adding myself to the interested developers now I have CLA approval. 
Also update list back to alphabetical order.

Add Daniel to interested developers

---

INTERESTED_DEVELOPERS.md
spec/GraphQLOverHTTP.md

Clarify support of UTF-8 and other encodings

---

rfcs/GraphQLOverWebSocket.md

https://github.com/enisdenjo/graphql-ws/pull/457

[GraphQL over WS] Recommend close event for rejecting connections

---

rfcs/GraphQLOverWebSocket.md

https://github.com/enisdenjo/graphql-ws/pull/469

[GraphQL over WS] Few typos

---

working-group/agendas/2023/2023-09-28.md

3rd Thursday now has a regular WG meeting, so I've moved us to the 4th Thursday.
Interested parties:
- @JoviDeCroock re: persisted operations
- @michaelstaib + the Guild re: ... I'll let them say.
- @enisdenjo re: graphql-http
Also if there's enough time left I'd like us to discuss what's left for us to move this to the next stage.
cc @abernix @balshor @benjie @deinok @erikwittern @jaydenseric @michaelstaib @mike-marcacci @mmatsa @shane32 @sjparsons @spawnia @sungam3r @touchstone117 @enisdenjo @JoviDeCroock

Add a GraphQL-over-HTTP WG meeting - September 28th

---

rfcs/PersistedOperations.md

Small wording change to improve grammar here

improve wording for absence in persisted-operations

---

working-group/agendas/2023/2023-09-28.md

Will bring this up during the next scheduled meeting

remove self from October meeting

---

working-group/agendas/2023/2023-10-26.md

I'd like to review remaining issues and discuss with implementors how they feel about the current status, especially now that we have a year of experience with it. I, personally, think it's pretty much ready to advance.
cc @enisdenjo especially.

Add "Advancing the spec to stage 2" to October WG

---

.github/ISSUE_TEMPLATE/action-item.md
.github/PULL_REQUEST_TEMPLATE/agenda-attendance.md

Add issue and PR templates

---

working-group/agendas/2024/2024-01-25.md

Includes 3 meeting items already from the previous (cancelled) meeting.

Add January agenda

---

working-group/notes/2024/2024-01.md

There was only me and @JoviDeCroock at the meeting, which was not an optimal situation for notes to be taken. As always, you can watch the replay on YouTube.

Add notes for Jan 2024 WG

---

rfcs/PersistedOperations.md

chore: mark Persisted-operations RFC as superseded by the appendix

---

working-group/agendas/2025/01-Jan/30-graphql-over-http-wg-january-2025.md

Also added a couple discussion points. 
@benjie I don't want to steal your watershed thunder, feel free to change the name there (I added mainly as a reminder cause that felt like something that could use some discussion).

Add Martin to January's working group

---

working-group/agendas/2025/02-Feb/27-graphql-over-http-wg-february-2025.md

Can’t make it, it’s parents evening at school.

Remove Benjie from Feb agenda

---

package-lock.json
package.json
working-group/agendas/2025/03-Mar/27-graphql-over-http-wg-march-2025.md
working-group/agendas/2025/04-Apr/24-graphql-over-http-wg-april-2025.md
working-group/agendas/2025/05-May/29-graphql-over-http-wg-may-2025.md
working-group/agendas/2025/06-Jun/26-graphql-over-http-wg-june-2025.md

AI summaries are now enabled... It might take us a while to actually use them, but they're enabled. We should note this at the start of each meeting.

Upgrade wgutils; note AI summary tools
