- INTERESTED_DEVELOPERS.md
- README.md
- ROADMAP.md
This PR begins a Roadmap document with some initial items under scope and actions for v1.0. My intention is to collaboratively edit the scope and actions as part of the November meeting of the GraphQL over HTTP working group. After that, this PR will be updated to reflect the results.
Easy links for viewing updated files:
- [Roadmap](https://github.com/sjparsons/graphql-over-http/blob/roadmap-draft/ROADMAP.md)
- [Interested Developers](https://github.com/sjparsons/graphql-over-http/blob/roadmap-draft/INTERESTED_DEVELOPERS.md)
- [Spec](https://github.com/sjparsons/graphql-over-http/blob/roadmap-draft/README.md) (The only change is the the note at the top stating the status and linking to the ROADMAP)
> Roadmap, Scope and Actions for v1.0

- agendas/2019-11-21.md
Add agenda item to discuss scope/action plan for v1.0 of the spec at the November **GraphQL over HTTP** working group.
> SP: Discuss scope/action plan for v1.0 of spec

- ROADMAP.md
- working-group/README.md
- working-group/agendas/2019-11-21.md
- working-group/agendas/2019-12-17.md
- working-group/agendas/_template.md
This PR publishes the general schedule for the working group and sets up a folder for future files related to the working-group itself.
> Publish schedule and re-organize

- working-group/implementations.md
This PR adds an implementations doc that lists popular implementations of graphql over HTTP both on server and client side. I've used GitHub stars as a measure of popularity and ordered them by their present number of GitHub stars. This gives a rough idea of popularity and should help us focus our efforts on most popular implementations.
> Add GraphQL implementations doc

- ROADMAP.md
This PR proposes an updated Roadmap laying out what should be in v1 of the GraphQL over HTTP spec and what should come in subsequent versions. 
[View Proposed Roadmap](https://github.com/APIs-guru/graphql-over-http/blob/mvp-roadmap-proposal/ROADMAP.md)
---
The actions listed in the roadmap itself and high level and meant to be just enough to get an understanding of how we might achieve this version. These high level actions might be broken down and organized into a GitHub project where those wishing to be involved might be able to help contribute to the progress.
> V1 Roadmap Proposal

- INTERESTED_DEVELOPERS.md
I've previously been interested and involved in previous meetings, but didn't notice this file until now.  I've therefore added myself in this commit! 😄 
Note: The instruction in the document states that we should order alphabetically by name though it doesn't include names, per se, just GitHub usernames.  I've therefore added myself alphabetized according to GitHub username, which seems to be the standard practice so far, but happy to adjust.
(Fwiw though, I won't be able to attend tomorrow's meeting. 😬)
> Add myself to INTERESTED_DEVELOPERS.md.

- working-group/implementations.md
- Changed the wording to define implementations more broadly than just GraphQL servers and clients, to also include middleware, etc.
- Updated the project star counts and reordered accordingly. High star count projects now have exact numbers, not just the approximations GitHub displays.
- Listed the [`graphql-upload`](https://github.com/jaydenseric/graphql-upload), [`apollo-upload-client`](https://github.com/jaydenseric/apollo-upload-client) and [`graphql-react`](https://github.com/jaydenseric/graphql-react) projects.
- Misc. formatting tweaks and fixes.
This actions a discussion point in the [2019-12-17 meeting](https://github.com/APIs-guru/graphql-over-http/blob/master/working-group/agendas/2019-12-17.md).
> Update the implementation lists

- working-group/agendas/2020-02-25.md
Also adds an agenda item: Test runner PoC progress for [#57](https://github.com/APIs-guru/graphql-over-http/issues/57).
> Add Jayden Seric to the 2020-02-25 agenda

- working-group/agendas/2020-04-28.md
- working-group/agendas/_template.md
This month I made a mistake and set up the meeting for 1700 instead of 1900 UTC. One of our members, @jaydenseric in Australia wasn't able to join since it was 4am. I'm correcting this now so that we get it right in the future.
> Fix time of meetings to align with our plan

- working-group/test-suite.md
The document included in this PR proposes a beginning set of tests based on the current draft spec that can be implemented. All comments are welcome as we start to evolve this list. Especially things that I have not yet included.
https://github.com/APIs-guru/graphql-over-http/issues/69
> Tests to build

- README.md
Relates to the discussion in https://github.com/APIs-guru/graphql-over-http/issues/91
@ghmcadams  @ralfhandl
> Clarify URL requirements

- INTERESTED_DEVELOPERS.md
- working-group/agendas/2020-08-25.md
The `graphql-transport-ws` repository has been renamed to `graphql-ws`. This PR updates the links.
> Repo rename

- rfcs/IncrementalDelivery.md
This PR aims to amend a few things that were discovered upon implementation:
- `Content-Length` is not mentioned as a requirement from the multipart spec. The change will now reflect that the boundary is not the "start" of the part, but rather the end of the part. The first boundary being the end of the preamble. This will give clients a much more predictable "I have enough body" to then begin parsing. Rather than wait for the next boundary to flush, which as per sample implementations wouldn't flush till the next chunk was written, potentially delaying the processing of that part. This now means a client can consume chunks till a boundary, then parse.
- the empty line after a body is also not accurate per multipart spec.
This will mean we're seeing a much tighter smaller payload, and …
> Spec edits for multipart @defer @stream around content-length

- INTERESTED_DEVELOPERS.md
- README.md
- ROADMAP.md
- spec/GraphQLOverHTTP.md
- working-group/README.md
Issue: https://github.com/graphql/graphql-over-http/issues/148
Updates include:
- Spec is in Preliminary Phase, with more frequent updates allowed.
- Working Group is using asynchronous communication.
- Spec is making changes to status-quo usage.
- Added GraphQL Foundation requested footer to README.
(with GraphQL-over-HTTP specific links)
> Update repo to reflect recent Working Group decisions

- spec/GraphQLOverHTTP.md
When executing a subscription operation a client expects multiple results which can best be expressed as a stream, while the incremental delivery RFC could be misused for describing how a stream of subscription events can be delivered to clients, it is clearly not the correct fit, as multipart requests are intended to be short-lived, while subscriptions could stay active for longer periods of time. Until alternative directions such as SSE events (as supported via graphql-helix and graphql-sse) are explored it might make sense to completely remove `subscriptions` from the list of allowed operations that can be executed via `POST`.
> remove subscriptions from allowed POST operations

- rfcs/GraphQLOverSSE.md
- [graphql-sse](https://github.com/enisdenjo/graphql-sse)
- _Feel free to add your implementation here!_
> GraphQL over Server-Sent Events

- rfcs/GraphQLOverWebSocket.md
- [graphql-ws](https://github.com/enisdenjo/graphql-ws)
- _Feel free to add your implementation here!_
> GraphQL over WebSocket

- .gitignore
- .prettierignore
- INTERESTED_DEVELOPERS.md
- README.md
- ROADMAP.md
- cspell.yml
- package.json
- spec/GraphQLOverHTTP.md
This copies over some of the standard setup from https://github.com/graphql/wg-template, notably the use of `prettier` to format the documents. This is, in part, because the GraphQL specification itself is now formatted with prettier.
You may want to review the commits individually, the last commit is simply the result of `yarn format`.
> Format documents with 'prettier'

- working-group/agendas/2022/2022-06-27.md
The next meeting of the GraphQL-over-HTTP working group has been scheduled, please add yourself to the agenda if you intend to attend.
Fixes #177
> Create agenda for June 27th WG

- spec/GraphQLOverHTTP.md
This is a normative change. Whilst adding the SHOULDs for #191 I realised that this should be a MUST, otherwise there's ambiguity in how `operationName=null` should be handled.
cc @glasser
> Clarify operationName in the query string

- spec/GraphQLOverHTTP.md
- spec/metadata.json
Following @glasser's feedback here https://github.com/graphql/graphql-over-http/pull/175#discussion_r917079660 I've split the "Invalid request body or parsing failure" example into three separate examples, and added spec-md references.
I believe this change does not include any normative changes, it's purely editorial.
Incidentally these H5's are horrible:
https://graphql.github.io/graphql-over-http/draft/#sec-Operation-cannot-be-determined
> [6.4.2.1.3](https://graphql.github.io/graphql-over-http/draft/#sec-Operation-cannot-be-determined) Operation cannot be determined
We should probably hoist to a higher level somewhere? (In a separate PR.)
> Split 'invalid request body or parsing failure' into three examples

- rfcs/IncrementalDelivery.md
According to RFC 1341, there is a CRLF *before* each `--BOUNDARY`, and *before* each payload chunk. That implies there should be a CRLF at the very beginning of the body before the first `--BOUNDARY`. (It also implies that if (as shown in the example) there is no blank link between each JSON chunk and the boundary after it, then the part should not be regarded as containing a trailing newline.)
> IncrementalDelivery: clarify exactly where CRLF is

- rfcs/GraphQLOverSSE.md
> [GraphQL over SSE] Drop mentioning GraphQL over HTTP content-types and rephrase

- spec/GraphQLOverHTTP.md
@sungam3r revealed some confusion in https://github.com/graphql/graphql-over-http/pull/224; this PR attempts to address the confusion by adding the word `encoded` to make it clear the parameters are encoded.
Fixes #224
> Clarify GraphQL-over-HTTP-GET

- rfcs/GraphQLOverWebSocket.md
https://github.com/enisdenjo/graphql-ws/pull/456
Original thinking was to support keeping the message size small by completely omitting the payload if nullish. But, that was an unnecessary limiting optimization.
Furthermore, allowing null values also keeps the spec more in line with the GraphQL over HTTP spec.
> Specifying `null` in JSON (or equivalent values in other formats) as values for optional request parameters is equivalent to not specifying them at all.
[_GraphQL over HTTP spec_](https://graphql.github.io/graphql-over-http/draft/)
> [GraphQL over WS] Allow null payloads

- spec/GraphQLOverHTTP.md
If someone believes that this spec contradicts the GraphQL spec, they should raise an issue so that either we fix it, or they don't rely on their faulty understanding.
> Raise issue on conflict

- working-group/test-suite.md
The `working-group/test-suite.md` document was a collection of our ideas around testing for an earlier version of the spec. It hasn't been touched in 3 years and the spec itself has evolved a lot since then, and its existence is causing confusion. This PR puts a notice at the top of the document to make it clear that it is out of date.
Fixes #246
> Indicate the WG test suite doc is out of date.

- spec/GraphQLOverHTTP.md
Reviewing @enisdenjo's GraphQL-over-HTTP audits, I realise that I made a mistake when drafting this specification. In my head, each time I wrote "request" I meant "GraphQL-over-HTTP request", i.e. one that roughly conforms to:
```ts
type GraphQLOverHTTPRequest = {
query: string;
operationName?: string | null;
variables?: Record<string, any> | null;
extensions?: Record<string, any> | null;
}
```
However this was not explicitly stated in enough places, the end result being that we now effectively state that if you send garbage at a GraphQL legacy server it _should_ return a 200 back at you. This was not my intent - my intent that 200 should only be used if the request conformed to the TypeScript shape above - `query` doesn't have to be parseable, and doesn't have to validate against your …
> `application/json` should only mandate 200 for _well-formed_ GraphQL-over-HTTP requests

- rfcs/IncrementalDelivery.md
HTTP/2 provides better mechanisms of data streaming and therefore prohibits the use of the Transfer-Encoding header (which is [recommended for GraphQL's Incremental Delivery](https://github.com/graphql/graphql-over-http/blob/main/rfcs/IncrementalDelivery.md#transfer-encoding-chunked)).
This PR explains the situation in greater detail and defines behaviour for HTTP/2 servers.
> Incremental Delivery over HTTP/2

- rfcs/PersistedOperations.md
This RFC intends to add `(Automatic) Persisted Operations` to the GraphQL over HTTP spec.
With persisted operations we can cater to some common needs
- Caching (determinstic document hash and url-size)
- Security (we can choose which requests to allow)
This requires us to agree on a way to `stringify` the document, a way to `hash` the document and an alteration to our current request parameters as this tries to add `documentId` and make `query` optional.
> RFC: persisted operations

- rfcs/PersistedOperations.md
Some CDNs (such as Cloudfront) do not support caching over POST. Thus, it's dramatically easier to hit the URL limit when sending variables over a query string.
I've added a paragraph to mention utilizing the POST body as an option for this or a HTTP header. I've personally used a `X-GQLVARS` header. Happy to include that naming here or leave it to the implementer on what to use
As I opened this document, my Grammarly extension corrected wording in some places. I've fixed them as the extension recommended, however I'm also happy to revert those changes and focus solely on the URL limit.
~~Note: I'm also creating this PR in order to sign the EasyCLA to participate in GraphQL Foundation meetings~~
> Address the URL limit for GET operations

- working-group/agendas/2023/2023-10-26.md
I've expanded the time to discuss persisted operations to enable discussing the spec edits in #264. Since it's now a bit longer, I've moved it after the 15 minute discussion so we can get that one out of the way first.
cc @JoviDeCroock
> Expand persisted operations discussion time

- rfcs/PersistedOperations.md
This to simplify discussing it in the WG meeting.
Additionally this adds a mention of the `Vary` header when the URL size is too long - #264 has a lot more detail so might be better to reconcile in there later on.
> Remove mentions of APQ and Stripping ignored tokens from Persisted Operations RFC

- spec/GraphQLOverHTTP.md
If the client issues `Accept: application/graphql-response+json, application/json` and the server does not support this for the request (e.g. the request uses `@stream`/`@defer` so needs a multipart response) then the server should be able to choose to respond with another suitable media type, for example `multipart/mixed;type=application/graphql-response+json`. Thanks to @michaelstaib for pointing out this oversight.
(Note: v1 doesn't explicitly specify `@stream`/`@defer` or `subscription` related concerns, but we should still be future proof where possible.)
> Server can choose the media type on Accept fail

- README.md
- ROADMAP.md
- spec/GraphQLOverHTTP.md
Fixes https://github.com/graphql/graphql-over-http/issues/272
The GraphQL-over-HTTP WG met yesterday and everyone is comfortable with advancing the spec to stage 2. We'll leave this PR open until the next WG to gather feedback, and if there are no major reservations expressed then we'll go ahead and advance it to stage 2 at [the November meeting](https://github.com/graphql/graphql-over-http/blob/main/working-group/agendas/2023/2023-11-23.md).
cc @abernix @balshor @benjie @deinok @erikwittern @jaydenseric @michaelstaib @mike-marcacci @mmatsa @shane32 @sjparsons @spawnia @sungam3r @touchstone117 @enisdenjo @JoviDeCroock
> Advance spec to Stage 2

- spec/GraphQLOverHTTP.md
Fixes #271
The `extensions` object exists so that vendors may add their own properties to requests/responses/errors/etc. All top-level keys are reserved by the spec. This PR makes this explicit for JSON-encoded requests.
@enisdenjo Will this break any of the existing implementations, other than Relay's persisted queries network layer recommendation?
> Make it clear that other keys are reserved

- rfcs/GraphQLOverSSE.md
https://github.com/enisdenjo/graphql-sse/pull/71
> GraphQLOverSSE: note including an empty data field in the complete message

- spec/GraphQLOverHTTP.md
Adds a concrete example to the variable coercion error
> Add example of variable coercion failure

- wg.config.js
- working-group/agendas/2025/02-Feb/27-graphql-over-http-wg-february-2025.md
- working-group/agendas/2025/03-Mar/27-graphql-over-http-wg-march-2025.md
- working-group/agendas/2025/04-Apr/24-graphql-over-http-wg-april-2025.md
There's a conflict with a GraphQL Foundation (non-public) meeting. Hopefully this change causes minimal disruption.
> Push GraphQL-over-HTTP meetings back by half an hour

- wg.config.js
- working-group/agendas/2025/04-Apr/24-graphql-over-http-wg-april-2025.md
- working-group/agendas/2025/05-May/29-graphql-over-http-wg-may-2025.md
- working-group/agendas/2025/06-Jun/26-graphql-over-http-wg-june-2025.md
Using UTC gives us swings in people's local calendars, let's stick to pacific.
> Switch to pacific time

- spec/GraphQLOverHTTP.md
This is an alternative fix to #327 and #322 that does away with the watershed entirely. I'm coming to believe the watershed was a mistake.
We:
1. Require that compliant clients supply an `Accept` header (whilst noting that servers may support non-compliant clients).
1. Require that compliant clients include `application/graphql-response+json` in their `Accept` header
1. Name any server that only supports `application/json` a "legacy server"
1. Recommend that all new servers support `application/graphql-response+json`
1. Recommend that servers support `application/json` if and only if they want to support legacy (now non-compliant) clients
It is currently a draft because I've not had time to fully vet it, just wanted to get my thoughts down - I wouldn't review the specific wording too …
> Remove watershed and prefer new format

- cspell.yml
- spec/GraphQLOverHTTP.md
Based on the conversation within the 7-25-2024 working group, I've proposed a non-normative note on security and compatibility.  Feel free to suggest changes to this text.
> Add security and compatibility notes

- cspell.yml
- spec/GraphQLOverHTTP.md
Follow up to:
- https://github.com/graphql/graphql-over-http/pull/303
I think it's important that we make sure that this section clearly sets out what is in or out of scope of the spec from a security point of view, whilst being very crisp on any reasoning added (for example, the reason that GET is not used for mutations is not _purely_ due to security concerns).
This PR aims to add clarity to this section, restructuring it and expanding some areas, whilst contracting others. It aims to clearly demarcate examples, and surfaces many potential issues without offering many solutions, making it clear that these issues are truly out of scope (and non-exhaustive).
Further, because this is intended to be a non-normative section, it tries to be more factual: it provides statements of fact, and …
> Revise non-normative notes section

- spec/GraphQLOverHTTP.md
Fix the Document Validation Failure examples to match the wording of the other examples.
> Fix consistency of examples

- spec/GraphQLOverHTTP.md
> Servers don't need to validate this, and in fact they should not since a client from a future spec version may send additional keys, which legacy servers should just ignore.
I think we should add this to the spec.  The main graphql spec did not state this explicitly for reserved names (those starting with `__`), and now any current GraphQL UI applications built on Apollo's graphql library crash if they see additional reserved names in the introspection result.  (I consider this a bug but 🤷‍♂️ ).  They should be built to ignore additional features added to the spec, and the spec should state this.
We could add something like this:
_Servers receiving a request with additional properties MUST ignore the additional properties when processing the request._
_Originally posted by @Shane32 in …
> State that additional properties are ignored

- spec/GraphQLOverHTTP.md
`implementor` -> `implementer`. Both are valid, but we try to be consistent.
> Link to extensions in the main spec (and fix spelling)
